### ISSUE TITLE
Setting struct as EventBus Target?

### ISSUE THREAD

**Issue by shshalom** [cesarferreira/SwiftEventBus#10]

**Comment by cesarferreira** [comment]
Can you elaborate please?

**Comment by shshalom** [comment]
Sure, most of my project is based on structs rather then classes, and EventBus can't accept struct base "classes" as target.

For now I've worked around this by using actual classes. it would be nice if there were a way to set structs as target as well.

**Comment by nmDejamobile** [comment]
;@shshalom Do you mean structs as "sender" param ? If yes, I agree it would be nice to pass complex data structures without the need of an object

**Comment by cesarferreira** [comment]
Hey guys,
To be honest I haven't touched Swift in like 2 years (full time android) and I don't quite have the time atm to re-learn it and learn the 2.0, if you guys can make a PR with the changes I'll merge it asap  😃

**Comment by shshalom** [comment]
@nmDejamobile Yes I do, @cesarferreira Sad to hear that, hope you'll get the time to get back to it, you did a great job here :-)

**Comment by shshalom** [comment]
Hey @cesarferreira and @nmDejamobile.

I finally had some time trying to make SwiftEventBus to work with structs, and i think I've made it!
with the following method you can post complicated structs as sender as well setting structs as target.

Allow me to show you how I would use it first, and then how it has been done:

```swift
public struct Employee{
    public var id:Int
    public var name:String
}

public struct EmployeeManager {
    
    private var list:[Int:Employee] = [:]
    
    public init() {
        var `self` = self //required to allow mutating list inside the handler
        EventBus<Employee>.main(self, name: "NewWorkerEvent", handler: { newWorker in
            if let worker = newWorker {
                 self.list[worker.id] = worker
                 print(worker.name)
            }
        })
    }
}


class ViewController: UIViewController {

   override func viewDidLoad() {
        super.viewDidLoad()
    
        _ = EmployeeManager()
       //Posting events with new structs....
        EventBus.post(name:"NewWorkerEvent", sender: Employee(id: 0, name: "UserA"))
        EventBus.post(name:"NewWorkerEvent", sender: Employee(id: 1, name: "UserB"))
        EventBus.post(name:"NewWorkerEvent", sender: Employee(id: 2, name: "UserC"))
        EventBus.post(name:"NewWorkerEvent", sender: Employee(id: 3, name: "UserD"))
    }
}
```

Now, the way I made it work:

I've created an EventObject that basically take what ever generic type. 

```swift
open class EventObject<T>:Any {
    var object:T!
    public convenience init (data:T) {
        self.init()
        self.object = data
    }
}
```

For the sake of this example I've created a generic class that allows passing any kind of object as the sender or as target.

```swift
open class EventBus<T> {
    
   open class func post(name: String, sender: T? = nil) {
        NotificationCenter.default.post(name: Notification.Name(rawValue: name), object:
            EventObject<T>(data:sender!))
    }
    
    @discardableResult
    open class func main(_ target: AnyObject, name: String, handler: @escaping (T?) -> Void) -> NSObjectProtocol {
        return SwiftEventBus.on(target, name: name, sender: nil, queue: OperationQueue.main, handler: { result in
            if let object:T = (result.object as? EventObject<T>)?.object {
                handler(object)
            }else{
                handler(nil)
            }
        })
    }
    
    @discardableResult
    open class func main<Target>(_ target:Target, name: String, handler: @escaping (T?) -> Void) -> NSObjectProtocol {
        
        let targetObject = EventObject(data: target)
        
        
        return SwiftEventBus.on(targetObject, name: name, sender: nil, queue: OperationQueue.main, handler: { result in
            if let object:T = (result.object as? EventObject<T>)?.object {
                handler(object)
            }else{
                handler(nil)
            }
        })
    }
}
```

Let me know what do you think,  and if you would like me to create PR.

**Comment by cesarferreira** [comment]
Looks good :)
can you create a pull request and write a few tests?

**Comment by shshalom** [comment]
Sure :-)

**Comment by cesarferreira** [comment]
I'll close this issue waiting for the PR :)

**Comment by shshalom** [comment]
No problem mate,I am sorry for the delay, I was and still am really busy with work.
I hope I'll have some time this weekend.
