### ISSUE TITLE
[Cococapods][SwiftEventBus 2.0.0] A dependency with an external source may not specify version requirements

### ISSUE THREAD

**Issue by imagepit** [cesarferreira/SwiftEventBus#14]
I want to install SwiftEventBus 2.0.0 by cocoapods, So I input Podfile below and execute `pod install`.

```
pod 'SwiftEventBus', '~> 2.0.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
```

But error is occured.

```
[!] A dependency with an external source may not specify version requirements (SwiftEventBus).
```

![](https://www.evernote.com/l/AB1UhJqPMs5HUbpPmBa4VlBsXquW2XE1lCMB/image.png)

please help me.

**Comment by owen19891030** [comment]
the some error

**Comment by cesarferreira** [comment]
Try like this: 

```
pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
```

**Comment by nunogoncalves** [comment]
Just remove the version from the podfile while you point to github.

`pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'` 

@cesarferreira publish the 2.0 version to cocoapods. :)

**Comment by imagepit** [comment]
@cesarferreira @nunogoncalves 
Thunks!
I did install new SwiftEventBus 2.0.0.
In my cate, I must update cocoapods and repo.(below)

```
pod repo update
gem install cocoapods --pre
pod update
```

**Comment by cesarferreira** [comment]
I think the correct sintax is:

```
pod 'SwiftEventBus',  :tag => '2.0.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
```
