### ISSUE TITLE
SwiftEventBus 2.0.0 only available for ios 10 

### ISSUE THREAD

**Issue by owen19891030** [cesarferreira/SwiftEventBus#17]
when I use cocoapods ,set ios plaform 9.0, then  the log:Specs satisfying the `SwiftEventBus (from `https://github.com/cesarferreira/SwiftEventBus.git`, tag `2.0.1`), SwiftEventBus (= 2.0.0)` dependency were found, but they required a higher minimum deployment target.
I try to set plaform 10.0 ,it's ok

**Comment by cesarferreira** [comment]
I downgraded to target 9 on `2.0.1`, can you confirm?

**Comment by Xopoko** [comment]
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `SwiftEventBus (from `https://github.com/cesarferreira/SwiftEventBus.git`, tag `2.0.1`)` required by `Podfile`
- `SwiftEventBus (= 2.0.1)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `SwiftEventBus (from `https://github.com/cesarferreira/SwiftEventBus.git`, tag `2.0.1`), SwiftEventBus (= 2.0.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by cesarferreira** [comment]
Just created a new project and it works fine, can you be more specific?

My podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yolo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftEventBus', :tag => '2.0.2', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'

end
```

it works with both `9.0` and `10.0`, are you still on `8.0`?

**Comment by Xopoko** [comment]
I confirm it.

**Comment by cesarferreira** [comment]
Awesome man 👍
