### ISSUE TITLE
Swift 1.2 Support

### ISSUE THREAD

**Issue by raulagrait** [cesarferreira/SwiftEventBus#2]
Seeing build errors when compiling with XCode 6.3 beta 3 / Swift 1.2:

`/Users/ragrait/ios/Rdio/Pods/SwiftEventBus/SwiftEventBus/SwiftEventBus.swift:48:43: Invalid use of '()' to call a value of non-function type 'UInt'`

This is happening in 3 different places, but they're all variants on this:

```
let id = ObjectIdentifier(target).uintValue()
```

Looks like the trailing parens cause a syntax error in Swift 1.2

**Comment by cesarferreira** [comment]
Hey @raulagrait thanks a lot for the heads up!
I'm don't usually download the XCode betas for stabillity reasons (bad experiences in the past).
I'll fix it when the 6.3 is released, so I'll keep this issue open

**Comment by manuelgomes2** [comment]
Hi. XCode 6.3 out!

**Comment by cesarferreira** [comment]
Hey @manuelgomes2 , I released an update like 15h ago, it should work fine ;) thanks for the heads up tho!
