### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by ThimoKl** [cesarferreira/SwiftEventBus#22]
'pod install' fails for a macOS project with this message:

`Pre-downloading: 'SwiftEventBus' from 'https://github.com/cesarferreira/SwiftEventBus.git', tag '2.1.2'`
`[!] The platform of the target '[...]' (OS X 10.12) is not compatible with 'SwiftEventBus (2.1.0)', which does not support 'osx'.`

**Comment by cesarferreira** [comment]
Because it's only supported for iOS :)
