### ISSUE TITLE
onMainThread not fired

### ISSUE THREAD

**Issue by malkabani** [cesarferreira/SwiftEventBus#27]
Hi

I use "SwiftEventBus.post" when user clicks on the notification and open the app.
but in another side "onMainThread" not fired.

is there an issue or I miss up some thing.

can you help me?

Thanks

**Comment by nunogoncalves** [comment]
Can you share more details please? Maybe post some code?

**Comment by malkabani** [comment]
The app is in killed (not running and not in background), and new notification arrived and user clicks on it in notification center,  it will open the app.
And notification handler is fired and read notification data.
this I call 
`SwiftEventBus.post("receiveChatNotification")`
but 

`SwiftEventBus.onMainThread(self, name: "receiveChatNotification") { (notification) in`  
`            print("receiveChatNotification")`
`        }`
not fired and didn't print anything on log.

**Comment by nunogoncalves** [comment]
Two things that come to my mind:
Are you sure the post gets called?

Who is the listener? AppDelegate or another ViewController? If it's another view controller, make sure it has been loaded, otherwise it doesn't exist, and therefore can't listen to the event, right? :)

**Comment by malkabani** [comment]
so it must make AppDelegate the listener?

**Comment by nunogoncalves** [comment]
Depends, on what kind of logic you want to implement. If you want to show something to the user you need to load your view controller before sending the post. If you want your view controller to be the listener it has to be loaded, right? If an object doesn't exist, it can't do much. :) 💀

**Comment by malkabani** [comment]
I need to open chatViewController after a user makes click on the notification.  with two situations ( an app is running and another viewController appear - an app is not running).

so I need to make appDelegate is the listener. is this best practices?

**Comment by nunogoncalves** [comment]
My advice is that you load your navigation (supposing you need to go through 3 ou 4 screens before reaching that screen responsible) and you either pass the information down the chain (app delegate instanciates root view controller, and passes that info, then root VC passes to VC1, which passes to your destination VC), or you make the post on the app delegate after you know the app delegate has been loaded. I'm not sure what the best practice is, it really depends on your case. 

You can also save that info on a variable (static var, user defaults, or even database...) and use it on the view controller when it loads.
