### ISSUE TITLE
How to use this in a pod spec?

### ISSUE THREAD

**Issue by SanyasiraoM** [cesarferreira/SwiftEventBus#30]
Hi @cesarferreira,

How to use this in pod spec as dependency?

**Comment by SanyasiraoM** [comment]
I'm using https://github.com/sabirvirtuoso/SwiftEventBus a fork of yours, Thank you

**Comment by cesarferreira** [comment]
it's here https://github.com/cesarferreira/SwiftEventBus#cocoapods
