### ISSUE TITLE
issue with updating UI with a SwiftEventBus.post fired on a background thread

### ISSUE THREAD

**Issue by ChristopherRyanCruz** [cesarferreira/SwiftEventBus#4]
I'm having an issue with updating UI with a SwiftEventBus.post fired on a background thread. 
The issue happens when i'm making a network request for authenticating a user. 

We have an event for when the user is authenticated. When the user is authenticated, we fire off a SwiftEventBus event(which looks to be done on a background thread). 

The completion handler for the subscriber to the authentication event also publishes an event to notify the UI to update, but the event never gets caught by it's subscriber. The view controller that subscribes to the "navigate" event set's the subscription handler's "onMainThread" to true, but method never seems to get called.

Am I supposed to ensure that events relate to updating UI need to be fired on the main thread, or is this a known issue?

**Comment by cesarferreira** [comment]
Hey @ChristopherRyanCruz, I have a suspicion regarding your situation... can you provide a sample of the code so I can have a better understanding of your problem?

**Comment by ChristopherRyanCruz** [comment]
https://github.com/ChristopherRyanCruz/SwiftEventBus-example 

here is an example using one of my class projects that consistently reproduces the issue. 
 you can test the code by setting a breakpoint in https://github.com/ChristopherRyanCruz/SwiftEventBus-example/blob/master/Rotten%20Tomatoes/MovieViewController.swift#L28 , and running the app via simulator. The event handler never gets fired off.

Details:

https://github.com/ChristopherRyanCruz/SwiftEventBus-example/blob/master/Rotten%20Tomatoes/MovieViewController.swift#L68
In `MovieViewController.swift` after a successful asynchronous call, I fire off a SwiftEventBus event "getReadyToUpdateUI", which is subscribed to with an `onBackgroundThread` handler by the same view controller:
https://github.com/ChristopherRyanCruz/SwiftEventBus-example/blob/master/Rotten%20Tomatoes/MovieViewController.swift#L24

The handler posts a "updateUI" SwiftEventBus event.
https://github.com/ChristopherRyanCruz/SwiftEventBus-example/blob/master/Rotten%20Tomatoes/MovieViewController.swift#L28
This event is subscribed to with an `onMainThread` by the same view controller, which proceeds to present a modal uiviewcontroller. The handler never gets hit, and the view controller never gets updated.

**Comment by cesarferreira** [comment]
Hey @ChristopherRyanCruz, @nunogoncalves just made a pull request which I've accepted and is already merged into the main branch that I think it will solve your problem.

Thanks to you both
