### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by tradingstratagem** [cesarferreira/SwiftEventBus#48]
Hi,
Swift Package Manager throws the following error:
<img width="543" alt="Screenshot 2019-10-05 at 16 57 27" src="https://user-images.githubusercontent.com/38089167/66256730-3bbc9680-e791-11e9-893e-4b56df999d35.png">

**Comment by cesarferreira** [comment]
@iKorich opened the pull request yesterday, can you take a look or can you open a pull request? I havent develop iOS in years

**Comment by cilki** [comment]
You can just set SPM to pull `master` instead of the `5.0.0` version tag for now. We need a new release...

**Comment by cesarferreira** [comment]
As I said, I haven't developed iOS in years, can you point me in the right direction or open a pull request? @cilki

**Comment by cilki** [comment]
@cesarferreira You can close this when you release `5.0.1`. The PR from @iKorich works, but Xcode doesn't see it if you depend on the latest release (which is the default option).

**Comment by cesarferreira** [comment]
just tagged and updated the readme https://github.com/cesarferreira/SwiftEventBus/releases/tag/5.0.1

I'll reopen this issue if it doesnt work for you, thanks everyone!
