### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.1 compiler:

### ISSUE THREAD

**Issue by ioskunal** [cesarferreira/SwiftEventBus#49]
I have installed SwiftEventBus in my project using Carthage and it shows me this error while running my project. I am using Xcode 11.1, also check this in 11.3.
Can someone please help how I can resolve this ?

**Comment by mingsai** [comment]
@ioskunal - This kind of error happens often and here is how I solve it most times: Open the project file separately and rebuild it. Make sure that you are using the correct version of Swift in the project settings. Upgrade to the latest version of Swift if necessary and fix any errors and then verify that it runs when you reintegrate it into your project. You might just want to do a drag and drop at this point to add it as a sub project.

**Comment by iKorich** [comment]
fixed in https://github.com/cesarferreira/SwiftEventBus/pull/54/

**Comment by cesarferreira** [comment]
released 5.1.0
