### ISSUE TITLE
is it compatible with ios7

### ISSUE THREAD

**Issue by EzimetYusup** [cesarferreira/SwiftEventBus#5]
how to use this lib for ios 7 ?

**Comment by cesarferreira** [comment]
@EzimetYusup this library is written in Swift and this language is only compatible on iOS 8+ so.. =/ I guess no luck there, google a little bit, I'm sure you can find an alternative for iOS 7

**Comment by iCyberon** [comment]
@cesarferreira Wait, this is totally wrong. Swift is compatible with iOS 7. You just need to copy the source folder (SwiftEventBus) into your Xcode project.
